version: '3.9'

services:
  notificationapi:
    container_name: notification-api
    hostname: notification-api
    network_mode: bridge
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: ../
      dockerfile: NotificationApi/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq

  notificationservice:
    container_name: notification-worker
    hostname: notification-worker
    network_mode: bridge
    image: ${DOCKER_REGISTRY-}notificationservice
    environment:
   #   - ASPNETCORE_ENVIRONMENT=Development
      - RABBIT_HOSTNAME=my-rabbit
    build:
      context: ../
      dockerfile: NotificationService/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq

  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   network_mode: bridge
   hostname: my-rabbit
   ports:
      - 5672:5672
      - 15672:15672




