version: '3.4'

services:
  notificationservice:
    network_mode: bridge
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: ../
      dockerfile: NotificationService/Dockerfile
