services:  
  rabbitmq:  
    image: rabbitmq:3-management  
    container_name: rabbitmq  
    hostname: "${BROKER_HOSTNAME}"  
    ports:  
      - "${BROKER_PORT}:5672"  
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  notificationservice:  
    container_name: notification-worker  
    hostname: notification-worker  
    image: ${DOCKER_REGISTRY-}notificationservice  
    build:  
      context: ../  
      dockerfile: NotificationService/Dockerfile  
    restart: on-failure  
    depends_on:  
        rabbitmq:
            condition: service_healthy 
    environment:  
      - MessageBroker__port=${BROKER_PORT}  
      - MessageBroker__address=${BROKER_HOSTNAME} 
      - PushoverConfiguration__endpoint=${PUSHOVER_ENDPOINT}
      - appToken=${PUSHOVER_APP_TOKEN}
      - userKey=${PUSHOVER_USER_KEY}
    
  notificationapi:
    container_name: notification-api
    hostname: notification-api
    ports:
        - 5671:5671
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: ../
      dockerfile: NotificationApi/Dockerfile
    restart: on-failure
    depends_on:  
        rabbitmq:
            condition: service_healthy 
    environment:  
      - MessageBroker__port=${BROKER_PORT}  
      - MessageBroker__address=${BROKER_HOSTNAME} 





