version: '3.9'

services:
  notificationservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MESSAGE_BROKER_QUEUE=notifications
      - MESSAGE_BROKER_ADDRESS=172.17.0.2
      - MESSAGE_BROKER_PORT=5672
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- D:\testdata\__a:/app/config:ro
  notificationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
