name: Publish Notification Api Docker Image  

on:  
  push:  
    branches:  
      - main  
    paths:  
      - 'NotificationApi/**'  
      - '.github/workflows/push-image-notification-api.yml'  

jobs:  
  build-and-push:  
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: ./source
    steps:  
      - name: Check out the repo  
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v1  
        with:  
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

      - name: Build and push Docker image  
        uses: docker/build-push-action@v2  
        with:  
          context: ./NotificationApi  
          file: ./NotificationApi/Dockerfile  
          push: true  
          tags: marteek/notificationapi:latest  