name: Publish Notification Api Docker Image    
  
on:  
  push:  
    branches:  
      - main  
  
jobs:    
  build-and-push:    
    runs-on: ubuntu-latest    
    steps:    
      - name: Check out the repo    
        uses: actions/checkout@v2    
  
      - name: Log in to Docker Hub    
        uses: docker/login-action@v1    
        with:    
          username: ${{ secrets.DOCKER_HUB_USERNAME }}    
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
        
      - name: List contents of the context directory    
        run: ls -la ./source    
        
      - name: List contents of the repository    
        run: ls -la    
        
      - name: Build and push Docker image    
        uses: docker/build-push-action@v2    
        with:    
          context: ./source    
          file: ./source/NotificationApi/Dockerfile    
          push: true    
          tags: |  
           marteek/notificationapi:latest  
           marteek/notificationapi:${{ github.sha }}  